---
title: "Virtual Environments"
author: "Tara Furstenau"
date: "04/23/2015"
output:
  html_document:
    theme: flatly
---
Often times a Python project will require a specific package version that is different than the global package. Virtual environments are helpful in this scenario because they create an isolated Python environment within a directory with its own set of packages.  If virtualenv is installed, this will allow a user to install packages using pip without requiring root access. 

To install virtualenv:
```
$ pip install virtualenv
```
Move to the project directory that you want to isolate within the environment
```
$ cd project_folder
$ virtualenv env_name
```
Specify which version of Python
```
$ virtualenv -p /usr/bin/python2.7 env_name
```
Activate the environment
```
$ source env_name/bin/activate
```
The name of the environment should now appear to the left of the shell prompt.
While inside the environment any packages that are installed using pip will be placed in the env_name directory.
```
(env_name)$ pip install package_name
```
To leave the virtual environment
```
$ deactivate
```
To delete a virtual environment 
```
$ rm -rf env_name
```
From [http://docs.python-guide.org/en/latest/dev/virtualenvs/](http://docs.python-guide.org/en/latest/dev/virtualenvs/)